### PR TITLE
fix: home link vertical alignment

### LINKED ISSUE #246: Home Link is off center
image
The text is not center aligned.

### PR DESCRIPTION
**Pull request by dreitzner**
closes #246 

Text will now be center aligened:

image

### CODE REVIEW

File: packages/site-kit/src/lib/nav/Nav.svelte [hunk 1]
```diff
@@ -204,6 +204,7 @@ Top navigation bar for the application. It provides a slot for the left side, th
 		background-size: auto 70%;
 		align-items: center;
 		padding-left: calc(var(--sk-page-padding-side) + 4rem);
+		padding-top: 5px; /* fixes font offset */
```
Comment (benmccann) [inline packages/site-kit/src/lib/nav/Nav.svelte:207]:
```suggestion
		padding-top: 5px; /* center vertically relative to logo */
```

**Comment by benmccann** [comment]
thanks!

**Comment by dreitzner** [comment]
You are welcome, it drove me crazy 🤪
